# Generated by Django 4.2.1 on 2023-05-23 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_character_alter_nonplayablecharacter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='first_person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='from_rel', to='organizer.character'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationship',
            name='second_person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='to_rel', to='organizer.character'),
            preserve_default=False,
        ),
    ]
