# Generated by Django 4.2.1 on 2023-05-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_relationship_first_person_relationship_second_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='gm_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='related_characters',
            field=models.ManyToManyField(blank=True, to='organizer.character'),
        ),
        migrations.CreateModel(
            name='LoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('time', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('gm_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('related_characters', models.ManyToManyField(blank=True, to='organizer.character')),
                ('related_locations', models.ManyToManyField(blank=True, to='organizer.location')),
            ],
        ),
    ]
