# Generated by Django 4.2.1 on 2023-05-23 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_location_gm_notes_alter_location_related_characters_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loreevent',
            old_name='description',
            new_name='summary',
        ),
        migrations.CreateModel(
            name='CampaignEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('previous_event', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizer.campaignevent')),
            ],
        ),
    ]
