# Generated by Django 4.2.1 on 2023-05-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0008_rename_statblock_nonplayablecharacter_stat_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_lore',
            field=models.TextField(blank=True, null=True),
        ),
    ]
