# Generated by Django 4.2.1 on 2023-05-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0009_location_location_lore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(default='notnull', max_length=128),
            preserve_default=False,
        ),
    ]
